# Generated by Django 5.2.16 on 2026-07-16 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loges', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='name',
            new_name='Registration',
        ),
    ]
